## https://developers.home-assistant.io/blog/2020/04/16/hassfest/
## https://hacs.xyz/docs/publish/action/

name: Validate with hassfest, HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: home-assistant/actions/hassfest@master
      - uses: hacs/action@22.5.0
        with:
          category: integration
